hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        auth0:
            type:           auth0
            client_id:      '%env(AUTH0_ID)%'
            client_secret:  '%env(AUTH0_SECRET)%'
            base_url:       '%env(AUTH0_BASE_URL)%'
            scope:          '%env(AUTH0_SCOPE)%'
        facebook:
            type:                facebook
            client_id:           '%env(FB_ID)%'
            client_secret:       '%env(FB_SECRET)%'
            scope:               "email"
            options:
                display: popup
                csrf: true
